"""
katsustats — A modernized backtest report module powered by Polars.

Usage:
    import katsustats
    katsustats.reports.full(returns, benchmark)              # console + plots
    katsustats.reports.html(returns, output="report.html")   # HTML report
    katsustats.reports.json(returns, output="report.json")   # JSON report
    katsustats.reports.markdown(returns, output="report.md") # Markdown report

    # Flat imports also work:
    from katsustats import sharpe, plot_cumulative_returns, html, json_report, markdown_report
"""

from __future__ import annotations

from . import plots, reports, stats  # noqa: F401

# plots
from .plots import (
    plot_cumulative_returns,
    plot_dow_distribution,
    plot_dow_winrate,
    plot_drawdown,
    plot_drawdown_periods,
    plot_eoy_returns,
    plot_monte_carlo,
    plot_monte_carlo_distribution,
    plot_monthly_heatmap,
    plot_return_distribution,
    plot_returns_vs_benchmark,
    plot_rolling_beta,
    plot_rolling_correlation,
    plot_rolling_sharpe,
    plot_rolling_sortino,
    plot_rolling_volatility,
    plot_snapshot,
    plot_yearly_returns,
)

# reports
from .reports import full, html
from .reports import json as json_report
from .reports import markdown as markdown_report

# stats
from .stats import (
    PeriodLabel,
    alpha_beta,
    avg_loss,
    avg_win,
    best_day,
    best_month,
    best_year,
    cagr,
    calmar,
    common_sense_ratio,
    consecutive_losses,
    consecutive_wins,
    correlation,
    cvar,
    day_of_week_stats,
    down_capture,
    drawdown_details,
    excess_return,
    exposure,
    gain_to_pain,
    information_ratio,
    kelly_criterion,
    kurtosis,
    martin_ratio,
    max_drawdown,
    monte_carlo_paths,
    monte_carlo_summary,
    omega_ratio,
    payoff_ratio,
    period_performance,
    period_performance_raw,
    positive_months_pct,
    positive_years_pct,
    probabilistic_sharpe,
    profit_factor,
    r_squared,
    recovery_factor,
    regime_stats,
    risk_of_ruin,
    rolling_beta,
    rolling_correlation,
    rolling_drawdown,
    rolling_sharpe,
    rolling_sortino,
    rolling_volatility,
    rolling_volatility_ratio,
    sharpe,
    skewness,
    sortino,
    summary_metrics,
    summary_metrics_raw,
    tail_ratio,
    total_return,
    treynor_ratio,
    ulcer_index,
    up_capture,
    value_at_risk,
    volatility,
    win_rate,
    worst_day,
    worst_month,
    worst_year,
)

__version__ = "0.8.0"

__all__ = [
    # submodules
    "plots",
    "reports",
    "stats",
    # stats
    "alpha_beta",
    "avg_loss",
    "avg_win",
    "best_day",
    "best_month",
    "best_year",
    "cagr",
    "calmar",
    "common_sense_ratio",
    "consecutive_losses",
    "consecutive_wins",
    "correlation",
    "cvar",
    "day_of_week_stats",
    "down_capture",
    "drawdown_details",
    "excess_return",
    "exposure",
    "gain_to_pain",
    "information_ratio",
    "kelly_criterion",
    "kurtosis",
    "martin_ratio",
    "max_drawdown",
    "monte_carlo_paths",
    "monte_carlo_summary",
    "omega_ratio",
    "payoff_ratio",
    "PeriodLabel",
    "period_performance",
    "period_performance_raw",
    "positive_months_pct",
    "positive_years_pct",
    "probabilistic_sharpe",
    "profit_factor",
    "r_squared",
    "regime_stats",
    "recovery_factor",
    "risk_of_ruin",
    "rolling_beta",
    "rolling_correlation",
    "rolling_drawdown",
    "rolling_sharpe",
    "rolling_sortino",
    "rolling_volatility",
    "rolling_volatility_ratio",
    "sharpe",
    "skewness",
    "sortino",
    "summary_metrics",
    "tail_ratio",
    "summary_metrics_raw",
    "total_return",
    "treynor_ratio",
    "ulcer_index",
    "up_capture",
    "value_at_risk",
    "volatility",
    "win_rate",
    "worst_day",
    "worst_month",
    "worst_year",
    # plots
    "plot_cumulative_returns",
    "plot_dow_distribution",
    "plot_dow_winrate",
    "plot_drawdown",
    "plot_drawdown_periods",
    "plot_eoy_returns",
    "plot_monthly_heatmap",
    "plot_monte_carlo",
    "plot_monte_carlo_distribution",
    "plot_return_distribution",
    "plot_returns_vs_benchmark",
    "plot_rolling_beta",
    "plot_rolling_correlation",
    "plot_rolling_sharpe",
    "plot_rolling_sortino",
    "plot_rolling_volatility",
    "plot_snapshot",
    "plot_yearly_returns",
    # reports
    "full",
    "html",
    "json_report",
    "markdown_report",
]
